name: coverage
on:
  workflow_dispatch:
  push:
    paths:
      - '**.go'
      - 'go.mod'
      - 'coverage.sh'
  pull_request:
    paths:
      - '**.go'
      - 'go.mod'
      - 'coverage.sh'

jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Setup Go SDK
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.21.0'
          check-latest: true
      - name: Run Go coverage
        run: ${{ github.workspace }}/coverage.sh
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          files: ${{ github.workspace }}/coverage.txt
          verbose: true
          fail_ci_if_error: true
