name: coverage
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/coverage.yaml'
      - '*.go'
      - '**/*.go'
      - 'go.mod'
      - 'qa_coverage.sh'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/coverage.yaml'
      - '*.go'
      - '**/*.go'
      - 'go.mod'
      - 'qa_coverage.sh'

jobs:
  codecov:
    runs-on: ubuntu-latest
    continue-on-error: true
    container:
      image: valord577/linux-cross-cgo:latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}
    steps:
      - name: clone source
        run: |
          git config --global --add safe.directory "*"

          git init
          git remote add x ${{github.server_url}}/${{ github.repository }}.git
          git fetch --no-tags --prune --no-recurse-submodules --depth=1 x +${{ github.sha }}
          git checkout FETCH_HEAD
      - name: coverage
        run: |
          ./qa_coverage.sh
      - name: required to codecov
        run: |
          apt update; apt install -y gpg
      - name: coverage to codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
          fail_ci_if_error: true
