name: golangci
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/golangci.yaml'
      - '.golangci.yml'
      - '*.go'
      - '**/*.go'
      - 'go.mod'
      - 'qa_golangci.sh'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/golangci.yaml'
      - '.golangci.yml'
      - '*.go'
      - '**/*.go'
      - 'go.mod'
      - 'qa_golangci.sh'

jobs:
  golangci:
    runs-on: ubuntu-latest
    continue-on-error: true
    container:
      image: valord577/linux-cross-cgo:latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}
    steps:
      - name: clone source
        run: |
          git config --global --add safe.directory "*"

          git init
          git remote add x ${{github.server_url}}/${{ github.repository }}.git
          git fetch --no-tags --prune --no-recurse-submodules --depth=1 x +${{ github.sha }}
          git checkout FETCH_HEAD
      - name: golangci
        run: |
          ./qa_golangci.sh
